<?php

namespace Database\Seeders;

use App\Models\Flag;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // \App\Models\User::factory(10)->create();
        //คำสั่งรัน php artisan db:seed --class=DatabaseSeeder
        $flag = [
            'Algeria.png',
            'Angola.png',
            'Benin.png',
            'Botswana.png',
            'Burkina_faso.png',
            'Burundi.png',
            'Cameroon.png',
            'Cape_verde.png',
            'Central_african_repub.png',
            'Chad.png',
            'Comoros.png',
            'Congo.png',
            'Cote_d_Ivoire.png',
            'Democratic_congo.png',
            'Djibouti.png',
            'Egypt.png',
            'Equatorial_guinea.png',
            'Eritrea.png',
            'Ethiopia.png',
            'Gabon.png',
            'Ghana.png',
            'Guinea.png',
            'Guinea_bissau.png',
            'Kenya.png',
            'Lesotho.png',
            'Liberia.png',
            'Libya.png',
            'Madagascar.png',
            'Malawi.png',
            'Mali.png',
            'Mauritania.png',
            'Mauritius.png',
            'Morocco.png',
            'Mozambique.png',
            'Namibia.png',
            'Niger.png',
            'Nigeria.png',
            'Rwanda.png',
            'Sao_tome_and_principe.png',
            'Senegal.png',
            'Seychelles.png',
            'Sierra_leone.png',
            'Somalia.png',
            'South_africa.png',
            'Sudan.png',
            'Swaziland.png',
            'Tanzania.png',
            'The_gambia.png',
            'Togo.png',
            'Tunisia.png',
            'Uganda.png',
            'Zambia.png',
            'Zimbabwe.png',

            'Afghanistan.png',
            'Azerbaijan.png',
            'Bahrain.png',
            'Bangladesh.png',
            'Bhutan.png',
            'Cambodia.png',
            'China.png',
            'East_timor.png',
            'India.png',
            'Indonesia.png',
            'Iran.png',
            'Iraq.png',
            'Israel.png',
            'Japan.png',
            'Jordan.png',
            'Kazakhstan.png',
            'Kuwait.png',
            'Kyrgyzstan.png',
            'Laos.png',
            'Lebanon.png',
            'Malaysia.png',
            'Maldives.png',
            'Mongolia.png',
            'Myanmar.png',
            'Nepal.png',
            'North_korea.png',
            'Oman.png',
            'Pakistan.png',
            'Palestine.png',
            'Philippines.png',
            'Qatar.png',
            'Saudi_arabia.png',
            'Singapore.png',
            'South_korea.png',
            'Sri_lanka.png',
            'Syria.png',
            'Tajikistan.png',
            'Thailand.png',
            'Turkmenistan.png',
            'United_arab_emirates.png',
            'Uzbekistan.png',
            'Vietnam.png',
            'Yemen.png',

            'Australia.png',
            'East_timor.png',
            'Fiji.png',
            'Indonesia.png',
            'Kiribati.png',
            'Micronesia.png',
            'Nauru.png',
            'New_Zealand.png',
            'Palau.png',
            'Papua_new_guinea.png',
            'Samoa.png',
            'Solomon_islands.png',
            'The_marshall_islands.png',
            'Tonga.png',
            'Tuvalu.png',
            'Vanuatu.png',

            'Antigua_barbuda.png',
            'Bahamas.png',
            'Cuba.png',
            'Dominica.png',
            'Granada.png',
            'Haiti.png',
            'Jamaica.png',
            'Pto_rico.png',
            'Republica_dominicana.png',
            'Sn_cristobal_nieves.png',
            'Sn_vicente_granadinas.png',
            'Sta_lucia.png',
            'Trinidad_tobago.png',

            'Belice.png',
            'Costa_rica.png',
            'El_salvador.png',
            'Guatemala.png',
            'Honduras.png',
            'Nicaragua.png',
            'Panama.png',

            'Albania.png',
            'Alemania.png',
            'Andorra.png',
            'ARY_Macedonia.png',
            'Austria.png',
            'Belgica.png',
            'Bielorusia.png',
            'Bosnia_y_Herzegovina.png',
            'Bulgaria.png',
            'Chipre.png',
            'Ciudad_vaticano.png',
            'Croacia.png',
            'Dinamarca.png',
            'Eslovaquia.png',
            'Eslovenia.png',
            'Espania.png',
            'Estonia.png',
            'Finlandia.png',
            'Francia.png',
            'Georgia.png',
            'Grecia.png',
            'Hungria.png',
            'Irlanda.png',
            'Islandia.png',
            'Italia.png',
            'Letonia.png',
            'Liechtenstein.png',
            'Lituania.png',
            'Luxemburgo.png',
            'Malta.png',
            'Moldova.png',
            'Monaco.png',
            'Montenegro.png',
            'Noruega.png',
            'Paises_bajos.png',
            'Polonia.png',
            'Portugal.png',
            'Reino.png',
            'unido.png',
            'Republica_checa.png',
            'Rumania.png',
            'Rusia.png',
            'San_marino.png',
            'Serbia.png',
            'Suecia.png',
            'Suiza.png',
            'Turquia.png',
            'Ucrania.png',
            'Union_europea.png',

            'Bermudas.png',
            'Canada.png',
            'Groenlandia.png',
            'Mexico.png',
            'Sn_pedro_miquelon.png',
            'Usa.png',


            'Argentina.png',
            'Bolivia.png',
            'Brasil.png',
            'Chile.png',
            'Colombia.png',
            'Ecuador.png',
            'Guyana.png',
            'Islas_malvinas.png',
            'Paraguay.png',
            'Peru.png',
            'Surinam.png',
            'Uruguay.png',
            'Venezuela.png',

        ];



        for($i = 0; $i < count($flag); $i++){

            $data = new Flag;
            $data->name_flag = $flag[$i];
            $data->save();
        }


    }
}
